# profile config
# 参考地址: https://www.baeldung.com/spring-profiles
spring:
  profiles:
    active: @spring.profiles.active@

# mybatis config
mybatis:
  config-location: classpath:sqlMapConfig.xml

# dubbo config
# 配置参考地址: https://yq.aliyun.com/articles/79277
dubbo:
  application:
    name: ${artifactId}
  registry:
    client: curator
  protocol:
    name: dubbo

# logging config
logging:
  level:
    tech.qijin.${artifactId}.db: DEBUG

